/**
 * Created by liuyc14 on 2016/9/27.
 */
export default {
    PRODUCT_CREATE: 'PRODUCT_CREATE',
    PRODUCT_SET_ONLYSTOCK: 'PRODUCT_SET_ONLYSTOCK',
    PRODUCT_SET_FILTERNAME: 'PRODUCT_SET_FILTERNAME'
};